=== chairazakaria/4d-concept/src/main/resources/projects.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="projects" type="projectsType"/>
    <xs:complexType name="projectType">
        <xs:sequence>
            <xs:element name="id" type="xs:string">
            </xs:element>
            <xs:element name="name" type="xs:string">
            </xs:element>
            <xs:element name="parent" minOccurs="0" type="xs:string">
            </xs:element>
            <xs:element type="tagsType" name="tags" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tagsType">
        <xs:sequence>
            <xs:element name="tag" maxOccurs="unbounded" minOccurs="0" type="xs:string">
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="projectsType">
        <xs:sequence>
            <xs:element type="projectType" name="project" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== chairazakaria/4d-concept/src/main/resources/projects.xml
<?xml version="1.0" encoding="UTF-8"?>
<projects
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="projects.xsd">
    <project>
        <id>1</id>
        <name>ROOT</name>
    </project>
    <project>
        <id>2</id>
        <name>I2020</name>
        <parent>1</parent>
        <tags>
            <tag>internal</tag>
            <tag>2020</tag>
        </tags>
    </project>
    <project>
        <id>3</id>
        <name>E2020</name>
        <parent>1</parent>
        <tags>
            <tag>external</tag>
        </tags>
    </project>
    <project>
        <id>4</id>
        <name>I2021</name>
        <parent>1</parent>
        <tags>
            <tag>internal</tag>
            <tag>2021</tag>
        </tags>
    </project>
    <project>
        <id>5</id>
        <name>B1C1</name>
        <parent>2</parent>
        <tags>
            <tag>2020</tag>
            <tag>2021</tag>
        </tags>
    </project>
    <project>
        <id>6</id>
        <name>B1C2</name>
        <parent>2</parent>
        <tags>
            <tag>2020</tag>
        </tags>
    </project>
    <project>
        <id>7</id>
        <name>B2C1</name>
        <parent>4</parent>
    </project>
    <project>
        <id>8</id>
        <name>B3C1</name>
        <parent>4</parent>
    </project>
</projects>
